### ISSUE TITLE
Add AirPlay device list

### ISSUE THREAD

**Issue by dippnerd** [Siddharth11/iTunes-Remote#6]
Would it be possible to add an AirPlay device list? I already looked into the AppleScript side and came up with the following:

```
module.exports = {
    getAirPlayProperties: `tell application "iTunes" to get properties of every AirPlay device`,
    getAirPlayDevices: `tell application "iTunes" to get name of every AirPlay device`,
    getSelectedAirPlayDevices: `tell application "iTunes" to get name of every AirPlay device whose selected is true`,
    getAirPlayDeviceVolume: `tell application "iTunes" to get sound volume of AirPlay device "${$val}"`,
    setAirPlayDeviceVolume(arr) {
        return `tell application "iTunes" to set sound volume of AirPlay device "${arr[0]}" to ${arr[1]}`
    }
  }
```

I'm not sure how to add it to the UI (but I did check and there is a Material Design icon for AirPlay), but could suggest putting it at the top center between the other two, sliding a panel down from the top (or could treat it like the Music app in iOS and put it at the bottom, sliding up from there).

I'm picturing a list of available AirPlay devices, with a checkbox or similar next to those that are already selected, with a volume slider for each device, largely similar to how iTunes already handles this:

<img width="300" alt="airplay" src="https://cloud.githubusercontent.com/assets/13409815/19276120/6ae1ef62-8fa3-11e6-85ad-60e007327383.png">

I'm not very familiar with the front end work but can totally give a hand on the back end. From what I've read there's a little bit more that AppleScript can handle in regards to AirPlay as well, so I'll research that further to see if it would make sense to add. The above can be phrased differently too depending on what needs returned.

**Comment by Siddharth11** [comment]
I'm not familiar with AirPlay, I use Android. You can fork the repo and add these commands, I can guide you with the frontend part if you need any help :)
